# Generated by Django 3.2.7 on 2021-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ML_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dataset_Title', models.CharField(max_length=30, null=True)),
                ('Train_Dataset_Upload', models.FileField(null=True, upload_to='Train_Dataset_Uploads/')),
                ('Test_Dataset_Upload', models.FileField(null=True, upload_to='Test_Dataset_Uploads/')),
                ('Train_Accuracy', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Validation_Accuracy', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Test_Accuracy', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
